### ISSUE TITLE
Project requires custom map/getDynamic and map/getStatic endpoints

### ISSUE THREAD

**Issue by MicrowaveJak** [Sethfire/foxhole-war-map#1]
It may be useful to note for users that this project is currently non-functional without the custom endpoints **map/getDynamic** and **map/getStatic** which appear to be (on your example site) returning an aggregated JSON of _all_ map data at once, though it works great with the test data provided.

Is the code for these endpoints something you'd be willing to share as a library or include in this project? I know I would certainly be grateful to benefit from your experience consuming the current [War API provided by Clapfoot](https://github.com/clapfoot/warapi), particularly if it respects ETags as described in their documentation.

**Comment by cchudant** [comment]
I ran into the same issue, so [I forked the project](https://github.com/cchudant/foxhole-war-map#foxhole-war-map) and changed the code so that it can directly consume the War API endpoint schema.

Of course, I don't directly consume the War API, instead I run an nginx instance (of which I have an [nginx.conf](https://github.com/cchudant/foxhole-war-map/blob/master/nginx.conf)/[docker-compose.yml](https://github.com/cchudant/foxhole-war-map/blob/master/docker-compose.yml)) with an in-memory 15 minutes cache

Thats quick and dirty but it works.

**Comment by Seblor** [comment]
I also had an issue with the missing endpoints code, and was not able to find a map for the second server [so I made my own fork](https://github.com/Seblor/foxhole-war-map), which supports the 2 servers.

Instead of making the 2 endpoints, I changed the paradigm and had the data in files instead of using endpoints, and then [I made an aggregator](https://github.com/Seblor/foxhole-data-aggregator) which updates the files at regular intervals.

The map/demo can be accessed here: https://foxhole.seblor.net/map/#2

**Comment by Sethfire** [comment]
So sorry for my late response, I did not notice this issue being opened. Must have missed the notification somehow. I only noticed the two project forks and was curious and noticed this. 

But yes, I am using a custom endpoint to get the data for the war map. The data is merged on the back-end server into a single JSON object for simplicity (I have uploaded the example data in the public folders as you have noticed). I am more than happy to upload that code onto the repository, give me a moment to do so.

There is also no implementation for multiple shards yet, because that only started recently. I am more than happy for anyone to modify the code and improve upon it, and I will try and update it onto the live website. I will add my discord, please contact me there so I can get back to you faster.
